language: node_js
node_js:
- '10'

dist: trusty
sudo: required
branches:
  only:
  - master

install:
- npm ci

cache:
  directories:
  - "$HOME/.npm"

before_script:
- npm install -g @angular/cli
script:
- ng build --prod
deploy:
  provider: s3
  access_key_id: AKIAVG6I3ANOYGM2T7X5
  secret_access_key:
    secure: hxUVdodJHHfUGcXj5GhPODJaQrIhAbucqFg+VnM916lnIiJmtasD3CEKNkD7rynh09N2G7pexx01HB6K3gL4ktGO7AJ93+p7prFYoic3xd198mP8AazaFbdi8vVhif9wSrOpIz1RcYxXCqD3IWDWAv4reKky3UbkWqZKG4dfUINuzhbVAWOcyotITsh9G2g0b71B2DBTaiOXFu7paFIa839B57aqqp4JQ+TcC2SVd5o/gdyTdyxE8HbLs+70o6f7fWmHsqmYFvfGIRWrybJoSs/I6UQZYd7/JNHfKqGnHD9n3CvAiWGv6d+mMMHwz7c5WSdahfKNJ0O5AqOn59asrjjq20nZz/vF0TdNkFjCPXPTY+XNG7btm8LfWyIeJtrT3Qa5XbAQnE29cFMnqW+ydOYgFTsRhwR4U4IuK9PmbqMVNddnNHhMCLCVdv4qY/lxsHmClt0fnLXYd/UBAS3HThcM4Zfyy4xThxQaKni2mwE/HBFfYtBESycwE7uatzLyH7YVSd7PHnExIoc0vkSoIVVzDR2K8qObmXiAzeRVf+E+eFc4Wwj6oW0X/jsEYknqZSNtFsWLn7ql1zfH/NRZH2ibT/yHTg8MV5po+WYWakrviD6VyXd2N9NXtADdg0wFnJOzBMJImHCjUStETLHxhuiMHwsSZuYjCKWOEme4Syo=
  bucket: amyhartzog.com
