language: node_js
node_js:
- '10'
dist: trusty
sudo: required

branches:
  only:
  - master

install:
- npm ci

cache:
  directories:
  - "$HOME/.npm"

script:
- ng build --prod

deploy:
  provider: s3
  access_key_id: <AWS_ACCESS_KEY>
  bucket: amyhartzog.com
  local_dir: dist
  secret_access_key: <AWS_SECRET_KEY>