language: node_js
node_js:
- '10'
dist: trusty
sudo: required
branches:
  only:
  - master
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
script:
- ng build --prod

deploy:
  provider: s3
  access_key_id: "<AWS_ACCESS_KEY>"
  bucket: amyhartzog.com
  secret_access_key:
    secure: occPnRk6AHGfMzNUh8jWiEWJWnwtu5ZaQV5LvhfgekGNWl5t7WhL04C12YHl2Y9j3yc8HtoYTs6NoJN4YWiQI+5l+iQ4/4Lu97ehbO81CQQBfPzV8EBHXL0KF0fqA0iJXIKP5Ts/FWFaS/8BDRxPEhmLVLus+Lz4LhguzBCWs+2IFN3aWdZLAmdw7pnVQKKyW9b3jtDUPJGzutBrQKqlf4aKT6kEJB64q/sH39uFvZGGKyq82xuAIU08ZyRd1vTm4MuQ9HewGSGXMtNmYXKbgAaKYR4/bbNE7vClZnTLwYznvPDaK3Os5kQExc76DzSxqG23Ukuc2xDKReaPNjX6YTKXwOmc9Swv3aBExpSkaXFI4LIHx8qCyL9AQVrwL+Zv3jTw1vg37WEBnnzs+yoi/WlMIZiFpmAdS1M4GlFbm6KN/LB/Lq3Rdlci8b6JsicEVXN4SHWcRuai4cvL3YapETXboQ+KYW27xT7fczRnh7jtQVh1rOyzN3kRjdEKIS4uWvRWLiExBBmX98fP/rnvDDWtiQXhXKsJJymKm0vGXEJiumKmBa7+RRipSIk+eLrQydR87NfScDYwUZVq1MO021ZtvkvHUrel5QOdwQ8L864M0Dyvge5SFPvNRj0sN5K6KsDvn1vRL0XhbV9YwZh68KEBwDDt8b0zAeW7jUtCY7s=
