language: node_js
node_js:
- '10'
dist: trusty
sudo: required
branches:
  only:
  - master
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
script:
- ng build --prod

deploy:
  provider: s3
  bucket: amyhartzog.com